name: smartcard
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  pdf: ^3.10.7
  printing: ^5.11.1
  flutter_bloc: ^8.1.3
  flutter_phoenix: "^1.0.0"
  easy_localization: ^3.0.3
  get_it: ^7.6.4
  page_transition: ^2.1.0
  google_fonts: ^6.1.0
  html: ^0.15.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  nfc_manager: ^3.3.0
  hex: ^0.2.0
  convert: ^3.1.1
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0+1
  sqflite: ^2.3.0
  lottie: ^2.7.0
  nb_utils: ^6.1.0
  flutter_bcrypt: ^1.0.8
  equatable: ^2.0.5
  barcode_scan2: ^4.3.0
  jwt_decoder: ^2.0.1
  connectivity_plus: ^5.0.2
  awesome_snackbar_content: ^0.1.3
  flutter_signature_pad: ^3.0.0
  flutter_animate:
  responsive_sizer:
  simple_gradient_text:
  flutter_svg:
  flutter_dialogs:
  flutter_svg_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  mobx_codegen: ^2.6.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json
    - assets/images/
    - assets/images/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
